# https://github.com/aspect-build/bazel-examples/blob/main/.github/workflows/ci.yaml

on:
  push:

# Bazelisk will download bazel to here, ensure it is cached between runs.
env:
  XDG_CACHE_HOME: ~/.cache/bazel-repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            "~/.cache/bazel"
            "~/.cache/bazel-repo"
          key: bazel-build-cache
      - run: |
          bazel \
          --bazelrc=$GITHUB_WORKSPACE/.aspect/bazelrc/ci.bazelrc \
          --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc \
          build \
          --remote_header=x-buildbuddy-api-key=${{ secrets.X_BUILDBUDDY_API_KEY }} \
          //...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            "~/.cache/bazel"
            "~/.cache/bazel-repo"
          key: bazel-test-cache
      - run: |
          bazel \
          --bazelrc=$GITHUB_WORKSPACE/.aspect/bazelrc/ci.bazelrc \
          --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc \
          test \
          --remote_header=x-buildbuddy-api-key=${{ secrets.X_BUILDBUDDY_API_KEY }} \
          //...
